# Generated by Django 3.2.4 on 2021-09-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=5)),
                ('residence', models.CharField(max_length=250)),
                ('profile', models.ImageField(upload_to='media')),
                ('achievements', models.TextField()),
            ],
        ),
    ]
