# Generated by Django 3.2.4 on 2021-09-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default='00000000000'),
        ),
        migrations.AddField(
            model_name='student',
            name='society',
            field=models.CharField(default='', max_length=600),
        ),
    ]
