# Generated by Django 3.2.4 on 2021-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=400)),
                ('desc', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=150)),
            ],
        ),
    ]
