# Generated by Django 3.2.4 on 2021-09-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='branch',
            field=models.CharField(default='', max_length=10),
        ),
    ]
