# Generated by Django 3.2.4 on 2021-09-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_timetable_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='days',
            field=models.CharField(default='', max_length=20),
        ),
    ]
