# Generated by Django 3.2.4 on 2021-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_timetable_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
        ),
    ]
