# Generated by Django 3.2.4 on 2021-09-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_notification_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='todoList',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=100)),
                ('duedate', models.DateField()),
            ],
        ),
    ]
