# Generated by Django 3.2.4 on 2021-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='branch',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='todolist',
            name='year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
