# Generated by Django 3.2.4 on 2021-09-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210917_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='classRep',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('roll', models.CharField(max_length=12)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
