# Generated by Django 3.2.4 on 2021-09-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_notification_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='tender',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
