# Generated by Django 3.2.4 on 2021-09-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_tender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tender',
            new_name='events',
        ),
    ]
